import Link from "next/link";
import { ArrowRightIcon, ArrowUpRightIcon } from "@phosphor-icons/react/dist/ssr";
import { Countdown } from "@/components/countdown";

function CompassPlate() {
  return <div className="compass-plate" aria-hidden="true"><svg viewBox="0 0 600 600" fill="none"><g className="contours" stroke="currentColor" strokeWidth="0.7">{[268, 243, 216, 186, 157, 125].map((r) => <ellipse key={r} cx="320" cy="294" rx={r} ry={r * 0.92} transform={`rotate(-26 320 294)`} />)}<path d="M30 300h540M300 30v540M110 110l380 380M110 490l380-380" /></g><circle cx="300" cy="300" r="214" stroke="currentColor" strokeWidth="1" /><circle cx="300" cy="300" r="204" stroke="currentColor" strokeDasharray="1 12" strokeWidth="5" /><g transform="rotate(24 300 300)"><path d="M300 88 342 258 512 300 342 342 300 512 258 342 88 300 258 258Z" fill="var(--hero)" stroke="currentColor" strokeWidth="1" /><path d="M300 88 300 300 258 258Z M512 300 300 300 342 258Z M300 512 300 300 342 342Z M88 300 300 300 258 342Z" fill="currentColor" /><path d="m300 166 24 110 110 24-110 24-24 110-24-110-110-24 110-24Z" fill="var(--ink)" opacity="0.12" /></g><circle cx="300" cy="300" r="19" fill="var(--hero)" stroke="currentColor" strokeWidth="2" /><circle cx="300" cy="300" r="8" fill="var(--ink)" /><g fill="var(--ink)" fontFamily="Public Sans, sans-serif" fontSize="12" textAnchor="middle"><text x="300" y="62">N</text><text x="551" y="305">E</text><text x="300" y="551">S</text><text x="50" y="305">W</text></g></svg><div className="plate-caption"><span>Curiosity. Evidence. Practice.</span><span>Find your direction.</span></div></div>;
}

export default function HomePage() {
  return <main id="main-content">
    <section className="hero"><div className="hero-copy"><h1>Directing the future of <em>healthcare.</em></h1><p>A student-led meeting of medical practice, scientific inquiry, and the people who will shape what comes next.</p><div className="hero-actions"><Link className="button" href="/registration">Registration <ArrowUpRightIcon size={19} aria-hidden="true" /></Link><Link className="text-link" href="/about">Discover COMPASS <ArrowRightIcon size={18} aria-hidden="true" /></Link></div><div className="hero-definition">Conference of Medical Practice<br />and Scientific Studies</div></div><CompassPlate /></section>
    <section className="event-strip" aria-label="Conference details"><Countdown /><div className="event-place"><strong>Beni Suef National University</strong><span>Faculty of Medicine and Surgery · Egypt</span></div><Link href="/agenda" className="text-link">The program <ArrowRightIcon size={18} aria-hidden="true" /></Link></section>
    <section className="home-intro"><div><h2>Good medicine starts<br />with good questions.</h2><span className="intro-rule" /></div><div className="intro-prose"><p className="lead">Between what we learn and how we care, there is a conversation worth having.</p><p>COMPASS brings medical practice and scientific studies into the same room. Built by students at BSNU, it is a place to ask better questions, share work, and find a direction of your own.</p><Link href="/about" className="text-link">Why we’re coming together <ArrowUpRightIcon size={18} aria-hidden="true" /></Link></div></section>
    <section className="explore-section"><div className="explore-heading"><h2>More than<br />a seat in the room.</h2><p>A program taking shape around learning, exchange, and student research.</p></div><div className="explore-list"><Link href="/agenda"><div><h3>Follow the conversation</h3><p>Talks, sessions, and space for questions.</p></div><span className="explore-detail">The agenda<ArrowUpRightIcon size={24} aria-hidden="true" /></span></Link><Link href="/speakers"><div><h3>Meet the minds behind it</h3><p>Speakers, their work, and the ideas they’ll share.</p></div><span className="explore-detail">Speakers & guests<ArrowUpRightIcon size={24} aria-hidden="true" /></span></Link><Link href="/posters"><div><h3>Make room for new research</h3><p>Student questions deserve a wider audience.</p></div><span className="explore-detail">Student posters<ArrowUpRightIcon size={24} aria-hidden="true" /></span></Link></div></section>
    <section className="sponsor-strip"><div><h2>Supported by shared ambition.</h2><p>Our conference partners will be announced here.</p></div><Link href="/sponsors" className="text-link">Sponsors & partners <ArrowUpRightIcon size={18} aria-hidden="true" /></Link></section>
  </main>;
}
